### ISSUE TITLE
Index sorting throws off iteration consistency

### ISSUE THREAD

**Issue by jerinv** [Dirguis/ipfn#17]
## Steps to Reproduce
I ran into this issue when running the IPFN algorithm over three dimensions, but my data actually has four dimensions to it. You can reproduce the issue by using this modified code of the pandas example:
```python
from ipfn import ipfn
import numpy as np
import pandas as pd

m      = np.array([1., 2., 1., 3., 5., 5., 6., 2., 2., 1., 7., 2.,
               5., 4., 2., 5., 5., 5., 3., 8., 7., 2., 7., 6.], )
dma_l  = [501, 501, 501, 501, 501, 501, 501, 501, 501, 501, 501, 501,
          502, 502, 502, 502, 502, 502, 502, 502, 502, 502, 502, 502]
size_l = [1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4,
          1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4]

age_l  = ['20-25','30-35','40-45',
          '20-25','30-35','40-45',
          '20-25','30-35','40-45',
          '20-25','30-35','40-45',
          '20-25','30-35','40-45',
          '20-25','30-35','40-45',
          '20-25','30-35','40-45',
          '20-25','30-35','40-45']

df = pd.DataFrame()
df['dma'] = dma_l
df['size'] = size_l
df['age'] = age_l
df['total'] = m

# This is the modified portion
new_class = df.copy()
df['class'] = 1
new_class['class'] = 2
df['total'] = df.total+1
df = pd.concat([df, new_class], ignore_index=True, sort=False)

xipp = df.groupby('dma')['total'].sum()
xpjp = df.groupby('size')['total'].sum()
xppk = df.groupby('age')['total'].sum()
xijp = df.groupby(['dma', 'size'])['total'].sum()
xpjk = df.groupby(['size', 'age'])['total'].sum()
# xppk = df.groupby('age')['total'].sum()

xipp.loc[501] = 52
xipp.loc[502] = 48

xpjp.loc[1] = 20
xpjp.loc[2] = 30
xpjp.loc[3] = 35
xpjp.loc[4] = 15

xppk.loc['20-25'] = 35
xppk.loc['30-35'] = 40
xppk.loc['40-45'] = 25

xijp.loc[501] = [9, 17, 19, 7]
xijp.loc[502] = [11, 13, 16, 8]

xpjk.loc[1] = [7, 9, 4]
xpjk.loc[2] = [8, 12, 10]
xpjk.loc[3] = [15, 12, 8]
xpjk.loc[4] = [5, 7, 3]

aggregates = [xipp, xpjp, xppk, xijp, xpjk]
dimensions = [['dma'], ['size'], ['age'], ['dma', 'size'], ['size', 'age']]

IPF = ipfn.ipfn(df, aggregates, dimensions)
df_new = IPF.iteration()
```
## Current Behavior
I added another primary key to the data, called "class", but the dimensions that are iterated over are still the same. In the new DataFrame, the following two rows exist:
| dma | size  | age | class | total|
|--|--|--|--|--|
|501|1|20-25|1|2|
|501|1|20-25|2|1|

The only difference between these two data points is their class. However, class is not a dimension that the algorithm runs over. Therefore, the ratios that are iteratively applied to these two data points should be the same. It follows that the value that the first row converges to should be larger than the value the second row converges to, since it's starting point was larger. This is not what happens - you get this instead:

| dma | size  | age | class | total|
|--|--|--|--|--|
|501|1|20-25|1|1.21543|
|501|1|20-25|2|1.89106|

As another check, you can divide these resulting values by their original values, and you will see the ratio is not the same.
## Expected Behavior
For the same two rows mentioned above, the expected result is the following:
| dma | size  | age | class | total|
|--|--|--|--|--|
|501|1|20-25|1|1.56207|
|501|1|20-25|2|0.781034|

## Possible Solution
I was able to a little debugging and noticed that *the new value after an iteration for a data point was then used as the starting value for a different data point in the next iteration*. 

I was able to put a **band-aid** solution over this and get the expected values by commenting out the index sort code. This is admittedly a dirty solution that impacts performance, but it returns the correct answer. I'm sure there's a better solution to this.

```python
            feat_l = []
            for feature in features:
                feat_l.append(np.unique(table_current[feature]))
            table_update.set_index(features, inplace=True)
            table_current.set_index(features, inplace=True)

            multi_index_flag = isinstance(table_update.index, pd.MultiIndex)
#            if multi_index_flag:
#                if not table_update.index.is_lexsorted():
#                    table_update.sort_index(inplace=True)
#                if not table_current.index.is_lexsorted():
#                    table_current.sort_index(inplace=True)

```

**Comment by Dirguis** [comment]
Hello,
Yes, I can see the behavior you are describing, but I feel that this issue is the result of not using the function properly and is outside the scope of the package. In this case, you are adding the column `class`, but you are not specifying any marginals on that class. As a result, the algorithm is not supposed to know nor care about that column. This is an under deterministic problem and as such, if you do not provide any marginals to deal with `class`, then `class` should not be part of the problem. Once the function without `class` has converged, then you can add the `class` column and split according to the strategy  that you want.

Let me know if that makes sense.

I will close the issue unless you want to provide more potential issues with this behavior

Thanks for the feedback!

Damien
