### ISSUE TITLE
Allow coarser aggregates

### ISSUE THREAD

**Issue by yiyange** [Dirguis/ipfn#18]
I am wondering it is reasonable to support the following use case:

I am doing some simulation using IPF to generate data at census block group level. However, I only have aggregates at county level for one of the dimensions. What I want to do is, for each iteration, sum the census block groups for a given county, and generate adjustment ratios at county level, and apply the same ratio for all census block groups in that given county. 

Essentially, I want to be able to use aggregate totals that are "coarser" or "smaller" than the corresponding dimension of the matrix.

Happy to put up an implementation of it for review if this is of interest.

**Comment by yiyange** [comment]
Following up...alternatively, users can disaggregate the aggregate total based on the existing distribution of the data points in that aggregate group. In other words, fake the desired the aggregate total to get the desired adjustment ratios.

**Comment by Dirguis** [comment]
Hello,

Do you have a running example to see exactly what you are talking about?
From what I understand, I think you are right in your second message though. I feel that the strategy is to generate the numbers that you need at the level that you need. Once you have them, replicate the numbers wherever they need to be replicated, then re-run. It is a 2 step process that would work I think

Let me know if I missed something!

Damien
