### ISSUE TITLE
Non-Uniform Weights

### ISSUE THREAD

**Issue by SDASL** [Dirguis/ipfn#19]
Hi Damien! 

Thanks so much for the package. 

Upon using the IPF algorithm it's come to my attention that some of the weights within a subgroup have large outliers. Is there any particular reason this is the case and why all subgroups in one category don't have the same or weights that are close to each other? 

Best.

SDASL

**Comment by Dirguis** [comment]
Hello!
Do you have an example I can use to reproduce the issues?
The algorithm is trying to match all marginals provided, across one or more dimensions. It is possible that marginals force outliers to exist.
In your case, I suspect that when you mention subgroup, you are looking at a particular dimension and value (like yellow in dimension colors). But that `yellow` is intersected by the other dimensions (like age, or gender). And if there is a big bias there, or if your initial distribution happens to be lacking examples for a dimension, that could result in outliers.

In the end, it is more about the problem than the algorithm itself.

Best,

Damien
